config/routes.rb
Rails.application.routes.draw do
  resources :recipes, only: [:index, :show]

  root "recipes#index"
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/application_resource.rb
require 'contentful'

class ApplicationResource

  space_id = Rails.application.credentials.contentful[:space_id]
  token = Rails.application.credentials.contentful[:token]
  @@client = Contentful::Client.new(
    space: space_id,
    access_token: token,
    api_url: 'cdn.contentful.com',
    raise_for_empty_fields: false
  )

  def self.all
    @@client.entries
  end

  def self.find(id)
    @@client.entry id
  end
end

app/models/recipe.rb
class Recipe < ApplicationResource
  def self.all
    super.select do |entry|
      entry.fields.dig(:title)
    end
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/recipes_controller.rb
class RecipesController < ApplicationController
  before_action :set_recipe, only: [:show]

  # GET /recipes
  # GET /recipes.json
  def index
    @recipes = Recipe.all
  end

  # GET /recipes/1
  # GET /recipes/1.json
  def show
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_recipe
      @recipe = Recipe.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def recipe_params
      params.fetch(:recipe, {})
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/recipes_helper.rb
module RecipesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>MarleySpoonRecipes</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <div class="main-container">
      <%= yield %>
    </div>
  </body>
</html>

app/views/recipes/index.html.erb
<div class="pure-g content">
  <h1 class="pure-u-1 recipes-list-greeting">Check out Marley Spoon's recipes!</h1>

  <div class="recipes-list">

    <% @recipes.each do |recipe| %>

      <%= link_to recipe_path(recipe.id) do %>

        <% if recipe.fields.has_key?(:photo) %>
          <div class="pure-u-1-1 recipes-list-photo">
            <img src="<%= recipe.photo.url %>" alt="<%= recipe.title %>">
          </div>
        <% end %>

        <div class="pure-u-1-1 recipes-list-title">
          <h3><%= recipe.title %></h3>
        </div>
      <% end %>

    <% end %>
  </div>
</div>

app/views/recipes/show.html.erb
<div class="pure-g content">
  <div class="pure-u-1-1 recipe-title-wrapper">
    <%= link_to recipes_path, class: 'pure-u back-link pill' do %>
      <span>Go Back</span>
    <% end %>
    <h2 class="recipe-title flex"><%= @recipe.title %></h2>
  </div>

  <% if @recipe.fields.has_key?(:photo) %>
    <div class="recipe-photo pure-u-1-1 flex">
      <img src="<%= @recipe.photo.url %>" alt="<%= @recipe.title %>" class="pure-img">
    </div>
  <% end %>

  <% if @recipe.fields.has_key?(:description) %>
    <p class="recipe-description pure-u-1-1 flex"><%= @recipe.description %></p>
  <% end %>

  <% if @recipe.fields.has_key?(:chef) %>
    <p class="recipe-chef pure-u-1-1 flex">by <%= @recipe.chef.name %></p>
  <% end %>

  <% if @recipe.fields.has_key?(:tags) %>
    <div class="pure-u-1-1 recipe-tags">

      <% @recipe.tags.each do |tag| %>
        <span class="recipe-tag pill"><%= tag.name %></span>
      <% end %>

    </div>
  <% end %>
</div>